## Import Libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
x=pd.read_csv(r"C:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\Data\x_train_processing.csv")

In [4]:
y=pd.read_csv(r"C:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\Data\target_processed.csv")

In [5]:
x_test=pd.read_csv(r"C:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\Data\x_test_processing.csv")

In [6]:
x.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       ...
       'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='str', length=308)

In [7]:
x=x.drop(columns=["Id"])

In [8]:
x.columns

Index(['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2',
       ...
       'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='str', length=307)

In [9]:
from sklearn.model_selection import train_test_split , cross_val_score
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [10]:
import xgboost as xgb

In [11]:
models={
    "Linear Regression":LinearRegression(),
    "Ridge Regression":Ridge(),
    "Lasso Regression":Lasso(),
    "Random Forest":RandomForestRegressor(n_estimators=100,random_state=42),
    "Gradient Boosting":GradientBoostingRegressor(n_estimators=100,random_state=42),
    "XGBoost":xgb.XGBRegressor(n_estimators=100,random_state=42)

}

In [12]:
print("--- Model Performance Comparison ---")

--- Model Performance Comparison ---

In [13]:
scoring='neg_root_mean_squared_error'

In [14]:
for name, model in models.items():
    scores=cross_val_score(model,x,y,cv=5,scoring=scoring,n_jobs=-1)
    avg_rmse=-np.mean(scores)
    std_rmse=np.std(scores)

    print(f"{name}:")
    print(f"Average Rmse:{avg_rmse}")
    print(f"Average Deviation:{std_rmse}")

Linear Regression:
Average Rmse:0.1285392256782924
Average Deviation:0.018265231079087337
Ridge Regression:
Average Rmse:0.11701729668733427
Average Deviation:0.007312159141173076
Lasso Regression:
Average Rmse:0.23461504961678736
Average Deviation:0.006017745231410117
Random Forest:
Average Rmse:0.1387701084378489
Average Deviation:0.005369340771114142
Gradient Boosting:
Average Rmse:0.12108730906951541
Average Deviation:0.005673980124946561
XGBoost:
Average Rmse:0.13898832499980926
Average Deviation:0.006666804785776759

In [15]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import RandomizedSearchCV
import numpy as np

gbr = GradientBoostingRegressor(random_state=42)

param_dist = {
    "n_estimators": [100, 200, 300, 500, 700],
    "learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
    "max_depth": [2, 3, 4, 5],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "subsample": [0.6, 0.8, 1.0],
    "max_features": ["sqrt", "log2", None]
}

random_search = RandomizedSearchCV(
    estimator=gbr,
    param_distributions=param_dist,
    n_iter=100,                 # Number of random combinations
    scoring="neg_root_mean_squared_error",
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)
print("--- Starting Hyperparameter Tuning (this may take several minutes)... ---")
random_search.fit(x, y)
print("\n--- Tuning Complete! ---")
print(f"Best RMSE found: {-random_search.best_score_:.4f}")
print("\nBest Hyperparameters found:")
print(random_search.best_params_)

--- Starting Hyperparameter Tuning (this may take several minutes)... ---
Fitting 5 folds for each of 100 candidates, totalling 500 fits

c:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\venv\Lib\site-packages\sklearn\ensemble\_gb.py:691: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

--- Tuning Complete! ---
Best RMSE found: 0.1155

Best Hyperparameters found:
{'subsample': 0.6, 'n_estimators': 700, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': None, 'max_depth': 3, 'learning_rate': 0.03}

In [25]:
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
xgb_model = XGBRegressor(
    objective="reg:squarederror",
    random_state=42,
    n_jobs=-1
)

param_dist1 = {
    "n_estimators": [100, 200, 300, 500, 700],
    "learning_rate": [0.01, 0.03, 0.05, 0.1, 0.2],
    "max_depth": [3, 4, 5, 6, 8],
    "min_child_weight": [1, 3, 5],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "gamma": [0, 0.1, 0.3, 0.5],
    "reg_alpha": [0, 0.01, 0.1, 1],
    "reg_lambda": [0.5, 1, 2, 5]
}

random_search1 = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_dist,
    n_iter=100,
    scoring="neg_root_mean_squared_error",
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

print("--- Starting Hyperparameter Tuning (this may take several minutes)... ---")
random_search1.fit(x, y)
print("\n--- Tuning Complete! ---")
print(f"Best RMSE found: {-random_search1.best_score_:.4f}")
print("\nBest Hyperparameters found:")
print(random_search1.best_params_)

--- Starting Hyperparameter Tuning (this may take several minutes)... ---
Fitting 5 folds for each of 100 candidates, totalling 500 fits

c:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [08:39:38] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:793:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

--- Tuning Complete! ---
Best RMSE found: 0.1144

Best Hyperparameters found:
{'subsample': 0.6, 'n_estimators': 700, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': None, 'max_depth': 3, 'learning_rate': 0.03}

In [17]:
final_model=random_search.best_estimator_

In [18]:
final_model.fit(x,y)

c:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\venv\Lib\site-packages\sklearn\ensemble\_gb.py:691: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

GradientBoostingRegressor(learning_rate=0.03, min_samples_leaf=4,
                          min_samples_split=5, n_estimators=700,
                          random_state=42, subsample=0.6)

In [19]:
test_ids=x_test["Id"]

In [20]:
x_test=x_test.drop(columns=["Id"])

In [21]:
x_test.isnull()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1455,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1456,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1457,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1458,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [22]:
x_test.isnull().sum()[x_test.isnull().sum() > 0]

BsmtFinSF1      1
BsmtFinSF2      1
BsmtUnfSF       1
TotalBsmtSF     1
BsmtFullBath    2
BsmtHalfBath    2
GarageCars      1
GarageArea      1
TotalSF         1
dtype: int64

In [23]:
columns=['BsmtFinSF1','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','BsmtFullBath','BsmtHalfBath','GarageCars','GarageArea']
for col in columns:
    x_test[col]=x_test[col].fillna(0)

In [28]:
x_test.drop(columns=["TotalSF"])

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,3.044522,4.394449,9.360741,5,6,1961,1961,0.000000,6.150603,4.976734,...,False,False,False,True,False,False,False,False,True,False
1,3.044522,4.406719,9.565775,6,6,1958,1958,4.691348,6.828712,0.000000,...,False,False,False,True,False,False,False,False,True,False
2,4.110874,4.317488,9.534668,5,5,1997,1998,0.000000,6.674561,0.000000,...,False,False,False,True,False,False,False,False,True,False
3,4.110874,4.369448,9.208238,6,6,1998,1998,3.044522,6.401917,0.000000,...,False,False,False,True,False,False,False,False,True,False
4,4.795791,3.784190,8.518392,8,5,1992,1992,0.000000,5.575949,0.000000,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,5.081404,3.091042,7.568896,4,7,1970,1970,0.000000,0.000000,0.000000,...,False,False,False,True,False,False,False,False,True,False
1455,5.081404,3.091042,7.546974,4,5,1970,1970,0.000000,5.533389,0.000000,...,False,False,False,True,True,False,False,False,False,False
1456,3.044522,5.081404,9.903538,5,7,1960,1996,0.000000,7.110696,0.000000,...,False,False,False,True,True,False,False,False,False,False
1457,4.454347,4.143135,9.253591,5,5,1992,1992,0.000000,5.823046,0.000000,...,False,False,False,True,False,False,False,False,True,False
1458,4.110874,4.317488,9.172431,7,5,1993,1994,4.553877,6.632002,0.000000,...,False,False,False,True,False,False,False,False,True,False

In [31]:
x_test["TotalSF"]=(
    x_test["1stFlrSF"]+
    x_test["2ndFlrSF"]+
    x_test["TotalBsmtSF"]
)

In [32]:
x_test["TotalSF"].isnull().sum()

np.int64(0)

In [33]:
predictions=final_model.predict(x_test)

In [34]:
actual_prediction=np.expm1(predictions)

In [35]:
print("Predictions transformed back to original dollar scale.")

Predictions transformed back to original dollar scale.

In [37]:
submission=pd.DataFrame({
    "Id":test_ids,
    "SalePrice":actual_prediction
})
submission.to_csv(r"C:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\Data\submission.csv",index=False)

## Xgboost final prediction

In [38]:
final_model1=random_search1.best_estimator_

In [39]:
final_model1.fit(x,y)

c:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [09:09:08] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:793:
Parameters: { "min_samples_leaf", "min_samples_split" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_features=None, max_leaves=None, min_child_weight=None,
             min_samples_leaf=4, min_samples_split=5, missing=nan,
             monotone_constraints=None, multi_strategy=None, ...)

In [41]:
xgb_prediction=final_model1.predict(x_test)

In [43]:
predict=np.expm1(xgb_prediction)

In [44]:
submission1=pd.DataFrame({
    "Id":test_ids,
    "SalePrice":predict
})
submission1.to_csv(r"C:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\Data\submission1.csv",index=False)

## Hyper parameter Tuning of Ridge Regression

In [45]:
ridge=Ridge(random_state=42)
param_dist = {
    "alpha": np.logspace(-4, 3, 100)   # 0.0001 to 1000
}
random_search2 = RandomizedSearchCV(
    estimator=ridge,
    param_distributions=param_dist,
    n_iter=30,
    scoring="neg_root_mean_squared_error",
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)
print("--- Starting Hyperparameter Tuning (this may take several minutes)... ---")
random_search2.fit(x, y)
print("\n--- Tuning Complete! ---")
print(f"Best RMSE found: {-random_search2.best_score_:.4f}")
print("\nBest Hyperparameters found:")
print(random_search2.best_params_)

--- Starting Hyperparameter Tuning (this may take several minutes)... ---
Fitting 5 folds for each of 30 candidates, totalling 150 fits

--- Tuning Complete! ---
Best RMSE found: 0.1136

Best Hyperparameters found:
{'alpha': np.float64(7.56463327554629)}

In [46]:
final_model3=random_search2.best_estimator_

In [47]:
final_model3.fit(x,y)

Ridge(alpha=np.float64(7.56463327554629), random_state=42)

In [49]:
log_prediction=final_model3.predict(x_test)

In [52]:
rdge_prediction=np.expm1(log_prediction)

In [57]:
submission2=pd.DataFrame({
    "Id":test_ids,
    'SalePrice':rdge_prediction
})
submission2.to_csv(r"C:\Users\mraj7\Desktop\AI_ML_Projeccts\House_Prices\Data\submission2.csv",index=False)